import {
    IsString,
    IsNumber,
    IsEmail,
    IsNotEmpty,
    Min,
    Max,
    Length,
    Matches
} from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

export class PaymentRequestDto {
    @ApiProperty({ example: '123e4567-e89b-12d3-a456-426614174000' })
    @IsString()
    @IsNotEmpty()
    productId: string;

    @ApiProperty({ example: 1 })
    @IsNumber()
    @Min(1)
    quantity: number;

    @ApiProperty({
        example: 'tok_test_12345_abcde',
        description: 'Card token generated by the frontend using Wompi API'
    })
    @IsString()
    @IsNotEmpty()
    @Matches(/^tok_(test|prod|stagtest)_\d+_[a-zA-Z0-9]+$/, {
        message: 'Invalid card token format'
    })
    cardToken: string;

    @ApiProperty({ example: 'customer@example.com' })
    @IsEmail()
    @IsNotEmpty()
    customerEmail: string;

    @ApiProperty({ example: '3001234567' })
    @IsString()
    @IsNotEmpty()
    @Length(7, 20)
    customerPhone: string;

    @ApiProperty({ example: 'John Doe' })
    @IsString()
    @IsNotEmpty()
    customerFullName: string;

    @ApiProperty({ example: 'Calle 123 # 45-67' })
    @IsString()
    @IsNotEmpty()
    @Length(10, 200)
    deliveryAddress: string;

    @ApiProperty({ example: 'Bogotá' })
    @IsString()
    @IsNotEmpty()
    deliveryCity: string;

    @ApiProperty({ example: 'Cundinamarca' })
    @IsString()
    @IsNotEmpty()
    deliveryDepartment: string;
}